# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = '▶▶ '

format = """ 
$sudo\
$jobs\
$directory\ 
$cmd_duration\
$battery\
$character """

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$time"""

add_newline = false

[git_branch]
symbol = '󰊢  '
truncation_length = 4
truncation_symbol = ''
ignore_branches = []

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_status]
conflicted = '󱃘 [#e64553]'
ahead = '[󱄟 ++\($count\)](#ca9ee6)'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '[󱚟 ](#7287fd)'
stashed = '📦'
modified = '[ ](#f9e2af)'
staged = '[++\($count\)](#CBA6F7)'
renamed = '[󱇧](#04a5e5)'
deleted = '[󱕖](#e64553) '

# Make promt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[❯](#6EA5AC)"
error_symbol = "[❯](#e64553)"
vimcmd_symbol = "[](#6EA5AC)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[directory]
home_symbol = ""
read_only = "  "
read_only_style = "#7287fd"

[directory.substitutions]
# "" = " "
"/Documents/links" = "  "
"/Sync/Documents" = "󱈖  "
"/Documents" = "󰈙"
"/Downloads" = ""
"/pictures" = " "
"/Videos/Movies" = "󱜇 "
"/Videos" = " "
"/Music" = " "
"dotfiles/scripts" = "󰯂 "
"dotfiles/.config/hypr" = " "
"dotfiles/.config/kitty" = "󰄛 "
"dotfiles/.config/yazi" = "󰇥 "
"dotfiles/.config/tmux" = " "
"dotfiles/.config/nvim" = " "
"dotfiles/.config/keyd" = " "
"dotfiles/.config/bat" = "󰭟 "
"dotfiles/.config/zathura" = " "

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 10
style = 'bold red'

[c]
symbol = ' '
style = "#04a5e5"

[python]
symbol = ' '
style = "bold yellow"

[rust]
symbol = ' '
style = 'bold red'

[lua]
symbol = ' '
style = 'bold blue'

[golang]
symbol = ' '
style = "#89B4FB"

[java]
style = '#dd7878'

[sudo]
symbol = '👿'
